name: users_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.3.3
  - sqlalchemy=2.0.30
  - pytest=8.2.2
  - pip
  - pip:
      - requests==2.31.0
      - python-dotenv==1.0.1
