name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_SERVICES: users analytics content api-gateway
  TEST_SERVICES: users analytics
  DEPLOY_SERVICES: users analytics api-gateway

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Construir y publicar imágenes Docker
        run: |
          set -e
          for service in $BUILD_SERVICES; do
            docker build -t ${{ github.repository }}/${service}:${{ github.sha }} alphapp.xyz/${service}/
            docker push ${{ github.repository }}/${service}:${{ github.sha }}
          done

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Instalar dependencias y ejecutar pruebas
        run: |
          set -e
          for service in $TEST_SERVICES; do
            pip install -r alphapp.xyz/${service}/requirements.txt
            pytest alphapp.xyz/${service}/tests/
          done

  deploy:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, production]
    environment:
      name: ${{ matrix.environment }}
      url: https://alphapp.xyz
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar kubectl
        uses: azure/setup-kubectl@v3
        with:
          install-location: 'client-tools'

      - name: Autenticarse en el clúster
        run: |
          set -e
          echo "${{ secrets['K8S_' + matrix.environment | upper + '_CONFIG'] }}" | base64 -d > kubeconfig-${{ matrix.environment }}.yaml
          export KUBECONFIG=$(pwd)/kubeconfig-${{ matrix.environment }}.yaml
          kubectl config current-context

      - name: Desplegar en el entorno ${{ matrix.environment }}
        run: |
          set -e
          for service in $DEPLOY_SERVICES; do
            kubectl apply -f deployments/${{ matrix.environment }}/${service}-deployment.yaml -n ${{ matrix.environment }}
          done

      - name: Esperar aprobación manual para producción
        if: matrix.environment == 'production'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.repository_owner }}
          instructions: "Por favor, aprueba el despliegue a producción antes de continuar."
